
modLoader="javafml" 
loaderVersion="[39,)"
license="MIT"

[[mods]] 
modId="unusualfishmod" 
version="0.2.0"
displayName="Unusual Fish Mod" 
logoFile="examplemod.png" #optional
credits="Thanks to Birdbasket and rusty_coconut for textures!"
authors="Peeko32213" 
description='''
A mod that adds a variety of new aquatic creatures and potion affects based around them.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"